module.exports = {
  roots: ["<rootDir>/src"],
  collectCoverage: true,
  collectCoverageFrom: [
    "src/**/*.{ts,tsx}",
    "!src/**/*.test.{ts,tsx}",
    "!src/mocks/**/*.{ts}",
    "!src/**/*.stories.{ts,tsx}",
    "!src/index.tsx",
    "!src/reportWebVitals.ts",
  ],
  coverageReporters: ["json", "lcov", "text", "html"],
  coverageDirectory: "coverage",
  coverageThreshold: {
    global: {
      lines: 0,
      branches: 0,
      functions: 0,
      statements: 0,
    },
  },
  setupFiles: ["<rootDir>/src/setupTests.ts", "react-app-polyfill/jsdom"],
  setupFilesAfterEnv: ["<rootDir>/src/setupTestsEnv.ts"],
  testMatch: ["<rootDir>/src/**/__tests__/**/*.{ts,tsx}"],
  testEnvironment: "jsdom",
  testRunner: "<rootDir>/node_modules/jest-circus/runner.js",
  transform: {
    "^.+\\.(js|jsx|mjs|cjs|ts|tsx)$": "<rootDir>/config/jest/babelTransform.js",
    "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
    "^(?!.*\\.(js|jsx|mjs|cjs|ts|tsx|css|json)$)":
      "<rootDir>/config/jest/fileTransform.js",
  },
  transformIgnorePatterns: [
    "/node_modules/(?!(onboarding|web-toolbox|log4js|devtools|react-datepicker|react-router|(@twilio(?!(-paste/animation-library)))))",
    "^.+.module.(css|sass|scss)$",
  ],
  modulePaths: [],
  moduleNameMapper: {
    "^react-native$": "react-native-web",
    "^.+\\.module\\.(css|sass|scss)$": "identity-obj-proxy",
    "^@app/(.*)$": "<rootDir>/src/app/$1",
    "^@hooks/(.*)$": "<rootDir>/src/hooks/$1",
    "^@mocks/(.*)$": "<rootDir>/src/mocks/$1",
    "^@context/(.*)$": "<rootDir>/src/context/$1",
    "^@site/(.*)$": "<rootDir>/src/site/$1",
    "^@src/(.*)$": "<rootDir>/src/$1",
    "^react($|/.+)": "<rootDir>/node_modules/react$1",
  },
  moduleFileExtensions: [
    "web.js",
    "js",
    "web.ts",
    "ts",
    "web.tsx",
    "tsx",
    "json",
    "web.jsx",
    "jsx",
    "node",
  ],
  watchPlugins: [
    "jest-watch-typeahead/filename",
    "jest-watch-typeahead/testname",
  ],
  resetMocks: true,
  testTimeout: 60000,
  snapshotSerializers: [
    "<rootDir>/config/jest/removeNonDeterministicAttributes",
  ],
};
